version: '3'
services:

    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - '3000:80'    

    postgres:
        image: 'postgres:latest' 
        environment: 
            - POSTGRES_PASSWORD=postgres
        restart: always
        
    redis:
        image: 'redis:latest'      
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./server   
        
        volumes: 
            - /app/node_modules
            - ./server:/app

        depends_on: 
            - postgres

        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres
            - PGPORT=5432
    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /app/node_modules
            - ./client:/app
        tty: true    
        
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            
    worker:
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes:
            - /app/node_modules
            - ./worker:/app
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379

